#!/bin/bash

set -euo pipefail

# This allows verifying a report generated by running the docker image in this repo

SCRIPT_PATH=$(dirname $(realpath $0))

if [ $# -ne 2 ]; then
  echo "Usage: $0 <report-file> <expected-challenge>"
  exit 1
fi

SNPGUEST_PATH="$SCRIPT_PATH/snpguest"
CHALLENGE=$2

if [ ! -f "$SNPGUEST_PATH" ]; then
  echo "Downloading snpguest"
  wget https://github.com/virtee/snpguest/releases/download/v0.10.0/snpguest -O "$SNPGUEST_PATH"
  chmod +x snpguest
fi

WORKDIR=$(mktemp -d /tmp/poc.XXXXX)
REPORT_PATH="$WORKDIR/report"
CERTS_DIR="$WORKDIR/certs"
REPORT=$(grep "Attestation report" $1 | cut -d " " -f3 | xxd -p -r >"$REPORT_PATH")

# Fetch certificates
$SNPGUEST_PATH fetch ca pem "$CERTS_DIR" -r "$REPORT_PATH"
$SNPGUEST_PATH fetch vcek pem "$CERTS_DIR" "$REPORT_PATH"

# Verify certificates
if ! $SNPGUEST_PATH verify certs "$CERTS_DIR" >/dev/null; then
  echo "Certificate verification failed"
  exit 1
fi

# Verify attestation, making sure it contains the challenge in the report data  field.
PADDED_CHALLENGE=$(printf "%-128s" "$CHALLENGE" | tr ' ' '0')
if ! $SNPGUEST_PATH verify attestation -r "0x$PADDED_CHALLENGE" "$CERTS_DIR" "$REPORT_PATH" >/dev/null; then
  echo "Attestation verification failed"
  exit 1
fi

$SNPGUEST_PATH display report "$REPORT_PATH"

rm -rf "$WORKDIR"
